name: docbot

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Create Documentation
      run: cargo doc 
    - name: Push Documentation
      run: |
        mkdir doc-src && git clone https://github.com/tmthecoder/docs doc-src
        cd doc-src
        echo "docs.tmthecoder.dev" > CNAME
        git config user.name  "Docbot"
        git config user.email "docbot@github.com"
        if [ -d xotp/ ]; then rm -Rf xotp/; fi
        cp -R ../target/doc/ xotp/
        echo "<meta http-equiv=\"refresh\" content=\"0; url=xotp\">" > xotp/index.html
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/docs
        git add .
        git commit -m "Updated documentation for xotp" --allow-empty
        git push secure-origin main
